### ISSUE TITLE
LINCS2020 complete perturbation object

### ISSUE THREAD

**Issue by adomingues** [yduan004/signatureSearchData#1]
Hi all,

I have a question regarding the data present in LINCS2 experiment object:

http://bioconductor.org/packages/release/data/experiment/vignettes/signatureSearchData/inst/doc/signatureSearchData.html#5_LINCS2_Signature_Database

```bash
library(ExperimentHub); library(rhdf5)
eh <- ExperimentHub()
query(eh, c("signatureSearchData", "lincs2"))
lincs2_path <- eh[['EH7297']]
rhdf5::h5ls(lincs2_path) 
```

From what I gather it contains only the signature for small molecule perturbations. I can use the excellent tutorial to generate the h5 object for all perturbations, listed in:

> The LINCS 2020 beta release data set contains 1.2 million signatures with 720,216 compound treatment GESs of 34,418 compounds, 34,171 gene over-expression on 4,040 genes, 318,208 gene knockdowns on 7,976 genes using shRNAs on 4,917 genes (177263) and CRISPR on 5,158 genes (140945).

But before I get started, I wanted to check first if an object with all the perturbations from the LINCS2020 beta set already exists - `level5_beta_all_n1201944x12328.gctx`. Is there one and if yes, where can I find it?

Cheers,
António

**Comment by brendangongol** [comment]
Hi Antonio,

That's correct, the LINCS2 experiment object contains only the data for small molecule perturbations. To use other types of perturbations, you will need to generate a separate database.  To accomplish this, I have set up a script which should work for you. You can download the data for crispr, shRNA, overexpression, or compound treatment using the websites under the download files section below.  The site where this information is located can also be found here: https://clue.io/releases/data-dashboard. The next section filters the data to include only exemplar signatures.  Finally, the last section uses the information from the filtered signatures to generate the HDF5 database.

Let me know if this answers your question.

Regards,
Brendan

testdirCustom <- "directory_Path"
dir.create(testdirCustom)
library(signatureSearch)

__Download files__
wget https://s3.amazonaws.com/macchiato.clue.io/builds/LINCS2020/level5/level5_beta_trt_xpr_n142901x12328.gctx
wget https://s3.amazonaws.com/macchiato.clue.io/builds/LINCS2020/level5/level5_beta_trt_sh_n238351x12328.gctx
wget https://s3.amazonaws.com/macchiato.clue.io/builds/LINCS2020/level5/level5_beta_trt_oe_n34171x12328.gctx
wget https://s3.amazonaws.com/macchiato.clue.io/builds/LINCS2020/level5/level5_beta_trt_cp_n720216x12328.gctx
download.file(url="https://s3.amazonaws.com/macchiato.clue.io/builds/LINCS2020/level5/level5_beta_trt_xpr_n142901x12328.gctx", 
              destfile = file.path(testdirCustom, "level5_beta_trt_xpr_n142901x12328.gctx"), 
              method = "wget", quiet = FALSE, mode = "w", cacheOK = TRUE,
              extra = getOption("download.file.extra"), headers = NULL)

__Level 5 profile summary__
library(data.table)
siginfo_beta <- fread("https://s3.amazonaws.com/macchiato.clue.io/builds/LINCS2020/siginfo_beta.txt");
fwrite(siginfo_beta, file.path(testdirCustom, "siginfo_beta.txt"))
siginfo_beta <- fread(file.path(testdirCustom, "siginfo_beta.txt"))
exemplar <- siginfo_beta %>% dplyr::filter(pert_type=="trt_xpr" & is_exemplar_sig == 1)

__Create LINCS database: Z-score Data in HDF5__
new_cid <- paste(exemplar$pert_id, exemplar$cell_iname, rep("trt_xpr", length(exemplar$cmap_name)), sep="__")
gctx <- file.path(testdirCustom, "level5_beta_trt_xpr_n142901x12328.gctx")
lincs_pathxpr <- file.path(testdirCustom, "lincsxpr.h5")
gctx2h5(gctx, cid=exemplar$sig_id, new_cid=new_cid,
        h5file=lincs_pathxpr, by_ncol=5000, overwrite=TRUE)

**Comment by adomingues** [comment]
Thanks @brendangongol. Quick follow up question: 

Why is the new_id created? I have seen it in all the tutorial, and assume it's only to make the signature IDs human-readable, but would like to confirm.

**Comment by brendangongol** [comment]
Hi Antonio,

The new_id, as we have described it, is created as a means of tracking treatments and cell types across samples. These labels become the column names of the database that is generated and, as you mentioned, make the column names human readable. In theory, you could customize the names of the columns using a different naming convention as long as all column names are unique.  

Regards,
Brendan
